### DISCUSSION TITLE
[FireMonkey/UserCSS] Cant make @include/@exclude regular expressions to work

### DISCUSSION THREAD

**Discussion by endtro** [erosman/support#700] [Q&A] [answered]
I can't seem to figure out how `@include` and `@exclude` works with regex. There's a handful of examples on the Internets of how it supposed to work, but none of them give me any clue about why it doesn't work in my case.

Here's a little example of what I've tried so far:
```
/* ==UserCSS==
@name             orange
@match            *://duckduckgo.com/?*q=*
@exclude          /oranges?/
@exclude          /\boranges?\b/
@exclude          /.+oranges?.+/
@exclude          /^.+oranges?.+$/
==/UserCSS== */

div {
  background-color: orange;
}
```
Now, if you visit the page https://duckduckgo.com/?q=oranges&ia=web, it should not be completely orange, but it is and I don't know why. Could you please explain me what am I doing wrong?

P.S. `@include` and `@exclude` with regular wildcards work fine, but sometimes it's just not good enough.

**Comment by erosman** [comment, marked as answer]
Please note ...

-  [FireMonkey](https://github.com/erosman/firemonkey) has it own separate repo now
- Browser APIs do not support Regular Expressions and the implementation in FireMonkey is a workaround in userscripts and least efficient
- Regular Expressions are not supported in UserCSS
- It would be most efficient to try something like:

```css
/* ==UserCSS==
@name             orange
@match            *://duckduckgo.com/?*q=*
@exclude-match    *://duckduckgo.com/?*q=orange*
==/UserCSS== */

div {
  background-color: orange;
}
```
