### ISSUE TITLE
[FireMonkey] Incorrect handling of @matches and @includeGlobs with port

### ISSUE THREAD

**Issue by CrendKing** [erosman/support#187]
## Steps to reproduce

1. Run a local web server at `http://127.0.0.1:12345`. Any non-standard http port works. Make sure to adjust in the following steps.
2. Create UserCSS with the following content. Observe the page at `http://127.0.0.1:12345/index.html`.
```
/*
==UserCSS==
@name           Test
@matches        *://127.0.0.1:12345/index.html*
@runAt          document_start
==/UserCSS==
*/
body {
    display: none !important;
}
```
3. Replace the `@matches` line with the following and observe the page.
```
@includeGlobs   *://127.0.0.1:12345/index.html*
```

## Expected result
The web page in step 2 should be unaltered and script count on FM icon should be 0, because for match patterns, host must not include a port number, thus the whole UserCSS should not apply.

The web page in step 3 should be completely blank and script count on FM icon should be 1, because the URL matches the glob.

## Actual result
The web page in step 2 is blank and script count on FM icon is 0. The web page in step 3 is unaltered and script count is 1.

## FM Version
1.35

**Comment by erosman** [comment]
Firefox/Chrome **Match patterns** does not allow port.

> [Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/match_patterns)
> 
> **host**
> 
> host must not include a port number.

**Comment by CrendKing** [comment]
That's exactly what I'm saying. `@matches` should not allow the port, yet the script applied. It is wrong.

Whereas `@includeGlobs` **does** allow port, yet the script did NOT apply. It is also wrong.

The only correct part is the script count on the icon.

**Comment by erosman** [comment]
Sorry... I misunderstood.

**Script Count**
There is no API to count the scripts that are injected. FM (and others) run a Regular Expression search on patterns and the RegEx shows script count 1.

**Injection**
1- `@matches        *://127.0.0.1:12345/index.html*`
There shouldn't be any injection. In fact it should cause an error with an ✗

2- `@includeGlobs        *://127.0.0.1:12345/index.html*`
Is the script injected?
Script count shows due to RegEx.

**Comment by CrendKing** [comment]
First, can you reproduce the issue here? If not, can you tell me which step can you not observe. Otherwise,

> Script Count
I don't care that much about incorrect count, though a consistency is always good.

> There shouldn't be any injection.
Yet in my test it is injected and no cross. That's part of the bug I'm reporting.

> Is the script injected?
No, it is not inject in my test. I thought it SHOULD be injected. If I'm wrong, can you explain why?

The expected result should be completely opposite of what I observed.

**Comment by erosman** [comment]
> First, can you reproduce the issue here?

I don't have a local server to test.

> I don't care that much about incorrect count, though a consistency is always good. Let's ignore the count for now and only deal with the injection part.

This part is handled by FM and I can work on it once the injection part is sorted.

**Injection**
Injection is performed by Firefox. FM has no control over it. FM passes the values of `@match` `@includeGlobs` etc to the [contentScripts.register()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contentScripts/register) (for CSS injection) as they are.

If it is injected or not, if there is an error or not, bug or not ... it is the Firefox API that processes it. Even if there is a bug, 


> No, it is not inject in my test. I thought it SHOULD be injected. If I'm wrong, can you explain why?

`@includeGlobs` is a subset of `content_scripts` `@match` in Firefox/Chrome. You must consider it logic process.
_Note: I must add that I brought up the shortcoming of this logic myself, long time ago. Chrome wrote the process as such (after adding globs to cater for GM type `include`) and Firefox copied it verbatim. I was actually told that the "ship has sailed long ago" and there is no possibility of changing the logic any more._

> [content_scripts](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts)
> 
> **must** contain a key named `matches`, which specifies the URL patterns to be matched in order for the scripts to be loaded;
> 
> ....
> 
> Since matches is the only mandatory key, the other three keys are used to limit further the URLs that match. To match the key as a whole, a URL must:
> 
> - match the matches property
> - AND match the include_globs property, if present
> - AND NOT match the exclude_matches property, if present
> - AND NOT match the exclude_globs property, if present
> 

Therefore, since it is a logical **AND** then you have to write it like this:

```
/*
==UserCSS==
@name           Test
@matches        *://*/*
@includeGlobs   *://127.0.0.1:12345/index.html*
@runAt          document_start
==/UserCSS==
*/
```


PS. the following is easer to notice when testing.

```CSS
/*
==UserCSS==
@name           Test
@matches        *://127.0.0.1:12345/index.html*
@runAt          document_start
==/UserCSS==
*/
body {
    border: 2px solid red;
}
```

Let me know the result of your testing.

**Comment by CrendKing** [comment]
I can confirm with
```
@matches        *://*/*
@includeGlobs   *://127.0.0.1:12345/index.html*
```
both the injection and script count works as expected. I didn't know the **AND** logic from the help. That text could use an update for clarification.

As to why `@matches  *://127.0.0.1:8200/ngax/index.html*` injects, it might be a Firefox bug, though I doubt they could overlook something so obvious, and nobody yet to find it out. I would be nice if someone 1) could reproduce this from FM; 2) write a skeleton addon to verify just `@match` with port number.

**Comment by erosman** [comment]
Can you test to see if **PORT** is processed or disregarded?

```css
/*
==UserCSS==
@name           Test
@matches        *://127.0.0.1:12345/index.html*
@runAt          document_start
==/UserCSS==
*/
body {
    border: 2px solid red;
}
```

```css
/*
==UserCSS==
@name           Test2
@matches        *://127.0.0.1:678/index.html*
@runAt          document_start
==/UserCSS==
*/
body {
    background-color: #ddd;
}
```

```css
/*
==UserCSS==
@name           Test3
@matches        *://127.0.0.1/index.html*
@runAt          document_start
==/UserCSS==
*/
body {
    text-align: center;
}
```
