### ISSUE TITLE
[FIREMONKEY]: Simple question

### ISSUE THREAD

**Issue by EstherMoellman** [erosman/support#267]
Hello @erosman my friend,

I can see you have been (and you still are) busy improving FireMonkey... congrats!, and always thanks for your work.

Today I have another one of my typical questions about script compatibilities and FireMonkey.
The new script is this one (very small): https://greasyfork.org/en/scripts/418897-global-ad-remover-using-referrerpolicy

When I install it in FireMonkey, at line 15, the corrector says to me to change "var" (deprecated) with "let" or "const". Please can you help me?
Also if possible, I would love to have your opinion about this script, if you think it's useful, useless etc. If it's an useful one, is it going to work in FireMonkey + Firefox?

As I said, I know you're busy, and my question is relevant only to me, so as usual feel free to answer me only if you want/can.

Thks in advance, happy holidays, and big hug! : )

**Comment by erosman** [comment]
Thank you for your kind comment. :+1: 

> When I install it in FireMonkey, at line 15, the corrector says to me to change "var" (deprecated) with "let" or "const". Please can you help me?

This is only a **recommendation** (mostly aimed towards script developers). It is better to avoid `var` and you wont find `var` anywhere in my own code. :wink: 
JavaScript introduced `const` & `let` to improve some shortcomings in `var`. Therefore `const` & `let` performance is much better.

> if possible, I would love to have your opinion ....

Only as general discussion .....

1. The script will work as it is in FireMonkey so there is no compatibility issue.

2. Since `GM.addStyle` is supported by all script mangers FM|GM|VM|TM, the script can be simplified to:

```js
// ==UserScript==
// @name         global ad remover using referrerpolicy
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  removes ads routed over the current domain (identified using referrerpolicy=unsafe-url)
// @author       cabtv
// @match        https://*/*
// @grant        none
// ==/UserScript==

GM.addStyle('[referrerpolicy="unsafe-url"] { display: none !important; }');
```

You can also use `GM_addStyle('[referrerpolicy="unsafe-url"] { display: none !important; }');` which is supported by FM|VM|TM but not GM.

3. Specially for FireMonkey, you can also do the same thing, **far more efficiently** as a userCSS e.g.

```css
/*
==UserCSS==
@name         global ad remover using referrerpolicy
@version      1.0
@description  removes ads routed over the current domain (identified using referrerpolicy=unsafe-url)
@author       cabtv
@match        https://*/*
@grant        none
==/UserCSS==
*/

[referrerpolicy="unsafe-url"] {
  display: none !important; 
}
```
4. Whether it works by eliminating some ads, has to be tested.
