### ISSUE TITLE
[FireMonkey] Current list sorting just alphabetically is hard to distinguish items

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#302]
Already reported [here](https://github.com/erosman/support/issues/258#issuecomment-737089454) by @CrendKing, at the time you said "*Lets hear from other users and decide*", so here I am creating a dedicated issue and voting for this change.

I believe that >90% of FM users only use the extension for UserScripts and that's why you don't see this being requested more often.

Current popup UI mixing scripts and styles is confuse for users who use both, even more for those who have many of each. I would even say that splitting the two types (scripts and styles) is more important than the current approach of splitting items matching current tab URL from the others that don't match. FM also mixes enabled and disabled items and maybe it shouldn't, but I'm not sure about this part.

Currently, to mitigate the issue, I'm using two styles. The first one acting in popup:
```css
  .main ul {
    display: flex;
    flex-direction: column;
  }

  .main ul li.js:not(.disabled) {
    order: 1;
  }

  .main ul li.js.disabled {
    order: 2;
  }

  .main ul li.css:not(.disabled) {
    order: 3;
  }

  .main ul li.css.disabled {
    order: 4;
  }
```
And other very similar in *options.html* → `Advanced` → `Custom CSS`, with `nav` replacing `.main`.

For Options page, using the style above in `Custom CSS` is enough, and there's also the filter checkboxes. But popup definitely should be redesigned. My suggestion:

- The two sections `Tab Scripts & CSS` and `Other Scripts & CSS` should be replaced by `Scripts` and `Styles`.
- All scripts and styles matching active tab would be displayed right away, including the disabled ones.
- After the last script there should be the item `Other Scripts`, so that clicking it would expand the list displaying non-matching scripts.
- The same for the `Styles` section.
