### ISSUE TITLE
Enabled box strange behavior

### ISSUE THREAD

**Issue by gbakeman** [erosman/support#328]
The enabled checkbox seems to exhibit strange behavior on FireMonkey 2.25 for Firefox (88.0.1). When I started my browser session, the script was disabled, but I could still see in the console that it was operating on a particular site. When I checked to Enable it, the check box begins rapidly flickering, and FireMonkey's "power usage" (according to about:performance) goes through the roof. If I restart my browser, this seems to resolve temporarily.

**Comment by erosman** [comment]
I will test it ...

- Is the script working?
- Does the popup show it as enabled?
- Does the option page show it as enabled?

**Comment by gbakeman** [comment]
Thank you for taking a look. The script is working insofar as the print command is reached, although the script seems to be executing whether it's enabled or not. I've just tried clicking the Run button, and FireMonkey made a popup that $ is not defined. I'm updating an old script for Greasemonkey 4.0, so maybe that's why. FireMonkey indicates that the script is disabled in the popup, and options page is where the flickering is occurring.

**Comment by gbakeman** [comment]
Original script:

```
// ==UserScript==
// @name         Remove ads on Gamepedia/Fandompedia
// @namespace    remove-ads-gamepedia
// @version      0.1
// @description  This will remove annoying ads on Gamepedia (aka Fandom wiki), it includes the removal of Gamepedia Pro bar and set the page width to 100%.
// @author       Joey_JTS
// @match        https://*.gamepedia.com/*
// @match        https://*.fandom.com/*
// @grant        GM_addStyle
// @require      https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
// ==/UserScript==

(function() {
    'use strict';

    $('#bodyContent').css('width', '100%');
    $('#btfheroContainer').remove();
    $('#siderail_terraria_gamepedia').remove();
    $('#atflb').remove();
    $('.ad-placement').remove();

    console.log('[NO ADS] Gamepedia Loaded.');
})();
```

I'd imagine there are multiple things wrong with it, although I still wonder why this behavior is occurring in FireMonkey.

**Comment by gbakeman** [comment]
Sorry for spamming comments, but I'd also like to add: when FireMonkey is in this odd state, the script executes many times, and spams my console with the log above.

**Comment by erosman** [comment]
TBH, the issue you described should relate to the userscript itself. Something in Firefox or FireMonkey seems to be the issue.

I have installed above script and run it and enabled/disabled it and still don't get any issues.

I suggest ...
- FireMonkey -> Export ... export the preferences
- Uninstall FireMonkey, restart browser (to clean up)
- Install FireMonkey
- Import preferences

Try and see if that helps.

> I'm updating an old script for Greasemonkey 4.0,

BTW ....... above script works much more efficiently as a userCSS with no need to jQuery. For example ...

```css
/*
==UserCSS==
@name         Remove ads on Gamepedia/Fandompedia
@version      0.1
@description  This will remove annoying ads on Gamepedia (aka Fandom wiki), it includes the removal of Gamepedia Pro bar and set the page width to 100%.
@author       
@match        https://*.gamepedia.com/*
@match        https://*.fandom.com/*
==/UserCSS==
*/

#bodyContent {
  width: 100%;
}

#btfheroContainer, #siderail_terraria_gamepedia,
#atflb, .ad-placement {
  display: none;
}
```
