### ISSUE TITLE
[FireMonkey] script with multiline comment /* */ in metablock doesn't work

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#393]
[This script](https://greasyfork.org/en/scripts/430593-recaptcha-solver-automatically-solves-recaptcha-in-browser/code) uses multiline comment within metablock. It fails silently in FM. It works fine with VM and TM. If you remove the comment, then the script works in FM.

I don't know why VM and TM support this, for me it's a mess, but... they do, so I think you should consider fix this to prevent very simple script compatibility issues like this one.

**Comment by erosman** [comment]
Having `*/` in include/exclude/match with `/* ..... */` as in UserCSS, breaks the code when inserted e.g.

```css
/*
==UserCSS==
@name           example
@match          *://*/*
@author         erosman
@version        1.0
==/UserCSS==
*/

body {
  border: 1px solid red;
}
```

Therefore, I change the `*/` to `* /` in metadata block before registering and that is the reason.

https://github.com/erosman/support/blob/b0930b9c8687e7f196f632a7f9c6b5661de4306b/content/background.js#L220-L223


I tried to keep the metadata block with minimum change in order to preserve the correct line numbers in console log.
I have to see if there is better way.
