### ISSUE TITLE
User CSS not applied on source.dot.net

### ISSUE THREAD

**Issue by ygoe** [erosman/support#421]
I've imported a style from the Stylus extension that now looks like this:

```css
/*
==UserStyle==
@name           source.dot.net Syntaxfarben
@run-at         document-start
==/UserStyle==
*/

@-moz-document domain('source.dot.net')
{
  #code .c
  {
    color: gray !important;
  }
}
```

Here's a website it applies to: https://source.dot.net/#System.Private.CoreLib/Collection.cs,281923b8611114ec

It should change the colour of all source comments from the default green to my custom grey. It used to work in Stylus (don't have it here anymore) and the HTML looks unchanged in this regard. But the comments on the page are still green. What's the problem here?

FireMonkey 2.41 in Firefox 96.0.3 on Windows 10

**Comment by erosman** [comment]
- There is no element that matches `#code .c` on that page so there is nothing to apply the CSS to.

- Although it is fine, being a simple userStyle, using the userCSS would be much more efficient .e.g
```css
/*
==UserCSS==
@name           source.dot.net Syntaxfarben
@match          *://source.dot.net/*
==/UserCSS==
*/

#code .c {
  color: gray !important;
}
```
