### ISSUE TITLE
[FireMonkey] Updating required style should re-register depending styles

### ISSUE THREAD

**Issue by pintassilgo** [erosman/support#424]
Create this style:

```css
/*
==UserCSS==
@name             test
@match            https://github.com/*
@version          1.0
==/UserCSS==
*/

body {
  background-color: red;
}
```

Open GitHub and you'll see a red background. Change the color in the code, like to `blue`. When you refresh the page, the change is applied, now background is blue. OK.

Now disable this style. And create a new one that imports it:

```css
/*
==UserCSS==
@name           test2
@match          https://github.com/*
@require        test
@version        1.0
==/UserCSS==
*/

/**/
```

Open GitHub, background is blue. Now update `test`, like reverting background to `blue`. Reload GitHub. Background is still `red`. FM should keep a list of dependent styles, so that in this case, when `test` was updated, `test2` must be re-registered to apply the change. Currently, I need to manually disable and re-enable `test2` to apply changes made in `test`.

**Comment by erosman** [comment]
Keeping track of `@require` dependency is possible but how often is it needed?
Data has to be kept in the memory for all dependencies all the time while the scenario is not something that happens that regularly. :thinking:

**Comment by pintassilgo** [comment]
Just add something like `dependencies` property in storage, so that only when a script/style is updated FM will run a cheap loop in this object . What's the problem in this? Zero impact in performance or in code complexity.

**Comment by erosman** [comment]
`@require` is already in the script storage. Possibilities are:
- When registering scripts, keep track of their dependencies in a cache in memory
- When a script is updated, search all enabled scripts to see if the updated script is in their `@require`, then unregister & reregister them

**Comment by pintassilgo** [comment]
Honestly, it can be any of the two options you listed, there's no practical difference. You may have a thousand styles and it will be instantly processed either way, with no impact.

**Comment by pintassilgo** [comment]
> Note: When someone is editing a script, they may make many changes and SAVE often, as we do to avoid losing changes. That would trigger many async unregister/re-register.

Is it not that way already? Always when you save an enabled script it is re-registered.

**Comment by erosman** [comment]
> Is it not that way already? Always when you save an enabled script it is re-registered.

Only for enabled scripts, not for dependencies.

**Comment by pintassilgo** [comment]
What's the difference? It will only trigger re-registering if it's a dependency of an enabled style, so ultimately it's enabled somehow. And you probably won't be editing with "many changes" if you don't intend to run it.

**Comment by erosman** [comment]
The dependency could be for multiple scripts.

- Imagine making boilerplate CSS or JS as base
- Above can be used as `@require` for many userCSS & userScript
- Editing the boilerplate would cause many async unregister/re-register
- Multiple edit/save can have performance impact on browser
- Note that re-register might involved remote  `@require`

You are thinking of 1 script using 1  `@require`, but consider 100s scripts using 1 local  `@require` and each have many external  `@require`. I would cause many `fetch` request.

**Comment by erosman** [comment]
There is another problem....

When people have tabs open (some have 1k+ tabs), un-registering scripts would mean scripts in all those tab will be removed but wont be inserted until refreshed. That can cause considerable discontent.

**Comment by pintassilgo** [comment]
I just had another practical experience of this issue.

I like a public style that I have installed. But I also like to do some personal changes over this style, so I created a new style that works like a fork, it has my modifications and `@require`s the original style. That way I can assure that my CSS is applied later, with prevalence when the same selector collides with original style.

Today, just after launching Firefox I noticed background color was different. I checked FM log and original style had been updated yesterday. I was online at the time and even after the update nothing had changed because of this issue, because an update to a disabled style which is required by an enabled style isn't applied instantly. The update was only applied when I closed and relaunched Firefox.

**Comment by pintassilgo** [comment]
> `@require` is already in the script storage. Possibilities are:
> 
>     * When registering scripts, keep track of their dependencies in a cache in memory

That's the fix I'd propose. In that case, when I created my style with `@require`, FM would store somewhere that info: "*style X is required by style Y*". So when "style X" updated, FM should look into "dependencies book" to see if "style X" is required by any enabled style. It will find out that "style X" is required by "style Y" which is enabled, so FM will unregister & register "style Y".

**Comment by erosman** [comment]
> When registering scripts, keep track of their dependencies in a cache in memory

In MV3, it is not possible to keep a cache in memory as background pages will be event pages in Firefox (and service workers in Chrome).

---

However ....... the `@require` process have been changed a while ago in v2.45.
FireMonkey no longer gets the remote `@require` CSS and instead uses `@import`.

That can work out in this case. Instead of keeping a copy of the original style, `@import` it.

As in [FireMonkey Help](https://erosman.github.io/support/content/help.html#require):

```css
/*
==UserCSS==
@name               Modifications
@description        CSS is fun
@match              http://www.example.com/*
@match              http://www.example.org/*
@version            1.0
==/UserCSS==
*/

/* --- Link to the original Style --- */
@import 'https://fonts.googleapis.com/css?family=Tangerine';
/* --- or --- */
@import url('https://fonts.googleapis.com/css?family=Tangerine');


/* --- Your modifications --- */
body {
  font-family: 'Tangerine', serif;
  font-size: 48px;
}
```

Firefox gets a copy, caches it and updates it when needed.

Try that and see how it works out.
