### ISSUE TITLE
Need help: How to suppress popup when scrolling down webpage

### ISSUE THREAD

**Issue by pstein** [erosman/support#487]
Most probably you could give me a hint on how to code a user script for a certain problem.

Lets start with a sample web page:

https://www.ilovefreesoftware.com/03/programming/how-to-use-windows-subsystem-for-android-in-android-studio-for-app-testing.html

When you load that page into Firefox and scroll down an advertizing popup appears.
How can I suppress this popup (for all web pages from https://www.ilovefreesoftware.com)?

If it pops up and you click the close "x" and reload THIS web page it does not appear again.
In order to re-produce the popup you have to close Firefox, restart and reload the webpage.

It is very annoying.
If the popup would appear immediately after load of the webpage a suppress would be no problem.
But it appears only delayed after scrolling down.

How can I suppress it from a user script?

**Comment by erosman** [comment]
It is quite easy using userCSS

```css
/*
==UserCSS==
@name           ilovefreesoftware
@match          https://www.ilovefreesoftware.com/*
@version        1.0
==/UserCSS==
*/

div[id^="elementor-popup-modal-"] {
  display: none !important;
}
```
