### ISSUE TITLE
[Firemonkey] Alternative to @-moz-document in CSS userscripts

### ISSUE THREAD

**Issue by Bluey26** [erosman/support#600]
Hello.

First of all i want to thank those behind this project, its awesome and it has a lot of different improvements, compared with the userscript addon i used back before.

I would like to know if by today there's any alternative to the '@-moz-document' thing for UserCSS scripts.
I have readed a few issues on here about the topic, and i understand that the function has been removed because mozilla deprecated it( i dont know why, if you know, i would like to know too :D ).

 I know that there's a conversion table in where i can see how to use an equivalent of this function, which consist mostly  of the '@match' fuctions .
But in my case, i would like to have 1 big css sheet in where i can turn on-off the 'dark mode' of some websites styles i have chosen.

The problem with this is that if i set the URLS in the match section, since some sites share css 'names/tags', the colors will be also shared in those sections of the sites, giving some undesirable colors and aspects in the websites affected.

In the other side, i know that in the JS userscripts section its possible to add 'if statements' which allows me to match the desired sites and hereby do something in that case.

Resuming all this, i was wondering, in case there's no actual alternative to match websites in the UserCSS scripts, if it will be possible to add 'hybrid' styles or allow somehow some small JS sections inside the CSS stylesheets, by means of make available strings like:

`if (url.includes(MYWEBSITECOM))
{
a:link {
  color: blue;
}
}`

Or something like that(css stylesheets inside the JS if statement).
I am not a programmer so i do not understand if this is really possible.

Thanks for all your work.
Bluey.

**Comment by erosman** [comment]
> I would like to know if by today there's any alternative to the '@-moz-document' thing for UserCSS scripts.
> I have read a few issues on here about the topic, and i understand that the function has been removed because mozilla deprecated it (I dont know why, if you know, i would like to know too :D ).

As mentioned in FireMonkey help under "Stylish/Stylus/xStyle Type UserStyle"
> Since Firefox 61, extensions can not use [@-moz-document](https://developer.mozilla.org/docs/Web/CSS/@document) (never supported on Chrome & other browsers)

`@-moz-document` was Mozilla version of [@document](https://lists.w3.org/Archives/Public/www-style/2004Aug/0135) which was originally planned for CCS3, but later postponed to CSS4 and finally dropped completely.

Although some addons still use it in order to keep backward compatibility with userStyles that were written long time ago, the usage is superficial.

UserStyle managers break each `@-moz-document` into segment and insert them individually. Therefore the following will be divided into 3 userStyles and then inserted.

```css
@-moz-document url-prefix("https://www.example1.com/") {
  h1 {
    color: green;
  }
}

@-moz-document url-prefix("https://www.example2.com/") {
  h1 {
    color: blue;
  }
}

@-moz-document url-prefix("https://www.example3.com/") {
  h1 {
    color: red;
  }
}
```

FireMonkey also does the same to support those type of userStyle and treat above as:

**css 1**
```css
/*
==UserCSS==
@name           one
@match          https://www.example1.com/*
==/UserCSS==
*/

h1 {
  color: green;
}
```

**css 2**
```css
/*
==UserCSS==
@name           two
@match          https://www.example2.com/*
==/UserCSS==
*/

h1 {
  color: blue;
}
```

**css 3**
```css
/*
==UserCSS==
@name           three
@match          https://www.example3.com/*
==/UserCSS==
*/

h1 {
  color: red;
}
```

With individual userCSS, there is more control. UserCSS in FireMonkey can also import other userCSS so users can create a CSS with common rules and share them with `@require`.

The only shortcoming is `@-moz-document regexp()` which is not supported. Therefore if a userStyle doesn't use `@-moz-document regexp` it can easily be written as userCSS in FireMonkey.

There is no problem with rewriting `@-moz-document url()`, `@-moz-document domain()`, & `@-moz-document url-prefix()` as `@match`.

Many `@-moz-document regexp()` can also be rewritten as one or more `@match`.

You can also use a userScript to insert CSS but userCSS has a far better performance.

If you give me an example, I will show you how it will work as a userCSS.

> The problem with this is that if i set the URLS in the match section, since some sites share css 'names/tags', the colors will be also shared in those sections of the sites, giving some undesirable colors and aspects in the websites affected.

There is no difference in the behaviour of userStyle and userCSS. They are both injected in a similar way.

> `if (url.includes(MYWEBSITECOM)) { a:link { color: blue; } }`

The `@match` does exactly the same, and more.

**Comment by Bluey26** [comment]
Thank you for the clear explanation.

Now i understand that the @-moz-require was some kind of split of the css code.

I have created some userCSS already, i was wondering how to load them with '1 click' or in a faster way than search all the CSS in the plugin menu and activate them one by one.


With the @require or the @resource does the code is 'loaded' into the same script or does it 'activates' separately?

I would like to have something like 1 tick in the addon bar, to activate all 'dark mode' userCSS, for example, since now i understand why it is not possible to combine them altogether in just one file without affecting in an undesirable way the other sites.

Is this possible?

**Comment by erosman** [comment]
`@require `or `@resource` is used to bring another JS/CSS into the current one, so all those items will be injected into whatever  page the importer runs on.
It wont work for what you have in mind.

## UserScript
Although not ideal, you can create a combined userScript e.g.

```js
// ==UserScript==
// @name          Dark Mode
// @match         https://www.example1.com/*
// @match         https://www.example2.com/*
// @match         https://www.example3.com/*
// ==/UserScript==

const css1 = 
`h1 {
  color: green;
}`;

const css2 = 
`h1 {
  color: blue;
}`;

const css3 = 
`h1 {
  color: ref;
}`;

switch (true) {
  case location.host.startsWith('https://www.example1.com/'):
    GM.addStyle(css1);
    break;

  case location.host.startsWith('https://www.example2.com/'):
    GM.addStyle(css2);
    break;

  case location.host.startsWith('https://www.example3.com/'):
    GM.addStyle(css3);
    break;
}
```

## UserStyle

FireMonkey supports userStyle and `@-moz-document url()`, `@-moz-document domain()`, & `@-moz-document url-prefix()` for compatibly with other userStyles.
It would have a better performance than the above userScript version.

You can create a combined userStyle (which would then be broken into 3 by FireMonkey) e.g.

```css
/*
==UserStyle==
@name          Dark Mode
==/UserStyle==
*/

@-moz-document domain('www.example1.com') {
  h1 {
    color: green;
  }
}

@-moz-document domain('www.example2.com') {
  h1 {
    color: blue;
  }
}

@-moz-document domain('www.example3.com') {
  h1 {
    color: red;
  }
}
```
