### ISSUE TITLE
firemonkey bypass img-src csp

### ISSUE THREAD

**Issue by Chrysanthemum536** [erosman/support#631]
how to bypass "img-src" csp when using custom css?

**Comment by erosman** [comment]
> [Add-on Policies: Development Practices](https://extensionworkshop.com/documentation/publish/add-on-policies/#development-practices)
> - Add-ons must not relax web page security headers, such as the Content Security Policy.

Firefox addons are not allowed to alter page CSP, but there are talks about CSP for userscript in MV3.

If you give an example page, I will try and see if there is a workaround.

**Comment by erosman** [comment]
userCSS works fine for me. 
_(Firefox Nightly 127)_

```css
/*
==UserCSS==
@name           puffyan
@match          https://vid.puffyan.us/*
@version        1.0
==/UserCSS==
*/

body {
  background-color: #aaa !important;
}
```

**Comment by erosman** [comment]
userCSS works fine for me. 
_(Firefox Nightly 127)_

```css
/*
==UserCSS==
@name           puffyan
@match          https://vid.puffyan.us/*
@version        1.0
==/UserCSS==
*/

body {
  background: #aaa url("https://github.com/erosman/support/raw/master/image/firemonkey.png") !important;;
}
```
